matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
    comments: false
    ignores: code
  sources:
  - '**/*.md'
  default_encoding: utf-8